sudo: required

language: c

services:
  - docker

before_install:
  - docker pull tg9541/docker-sdcc:V1.0.1

install:
  - docker run -v `pwd`:/home tg9541/docker-sdcc:V1.0.1 /bin/sh -c "sdcc --version ; sstm8 -version"

script: docker run -v `pwd`:/home tg9541/docker-sdcc:V1.0.1 /bin/sh -c "cd /home && make simload"

